namespace = { name = "my_game", default = "true" }

[manifest]
name = "my_game"

[project]
name = "my_game"
version = "0.1.0"

[world]
name = "Phaser Game"
description = "A verifiable Phaser game using Dojo"
seed = "phaser-game"

[env]
rpc_url = "http://localhost:5050/"
account_address = "0x517ececd29116499f4a1b64b094da79ba08dfd54a3edaa316134c41f8160973"
private_key = "0x1800000000300000180000000000030000000000003006001800006600"

[scripts]
init = "sozo build && sozo migrate"
test = "sozo test"

[[models]]
name = "Position"
path = "src/models.cairo"
type = "struct"
members = ["player", "vec"]
tag = "0x1"

[world_permissions]
my_game = ["actions"] 