[package]
cairo-version = "2.8.4"
name = "my_game"
version = "0.1.0"

[lib]
allowed-warnings = 99999

[cairo]
sierra-replace-ids = true

[[target.starknet-contract]]
sierra = true
casm = true
build-external-contracts = ["dojo::world::world_contract::world"]

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.0" }
starknet = "2.8.4"

[tool.dojo]
initializer = "src/lib.cairo"

[scripts]
build = "sozo build"
test = "sozo test" 